on: 
  release:
    types: [created]
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: demand
          SLACK_USERNAME: Pages
          SLACK_TITLE: Release
          SLACK_MESSAGE: ':rocket: Pages `${{ steps.get_release.outputs.name }}` released!'
          MSG_MINIMAL: true
